/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything: GPS, chrony and host stats */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GPS fix, DOPs and satellites */
        get: operations["gps_api_gps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps/satellites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Satellites in view */
        get: operations["satellites_api_gps_satellites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chrony": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** chrony tracking, sources, sourcestats, serverstats */
        get: operations["chrony_api_chrony_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chrony/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NTP clients seen by chrony */
        get: operations["clients_api_chrony_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Host temperature, load, uptime, memory */
        get: operations["system_api_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Time series of offsets, frequency, satellites and temperature
         * @description Up to HISTORY_HOURS (24 h): raw 5 s samples. Longer, up to HISTORY_DAYS (30 d): bucket averages of at most ~1500 points with offset min/max. The `X-History-Bucket-Seconds` header gives the resolution.
         */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 200 when gpsd and chrony are reachable, else 503 */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Online */
            online: number;
            /** Offline */
            offline: number;
            /** Burst Online */
            burst_online: number;
            /** Burst Offline */
            burst_offline: number;
            /** Unresolved */
            unresolved: number;
        };
        /** ChronyStatus */
        ChronyStatus: {
            /**
             * Ok
             * @description Last poll of chronyd succeeded
             */
            ok: boolean;
            /** Error */
            error: string | null;
            /**
             * Updated
             * @description Unix time of the last successful poll
             */
            updated: number | null;
            tracking: components["schemas"]["Tracking"] | null;
            /** Selected Source */
            selected_source: string | null;
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Sourcestats */
            sourcestats: components["schemas"]["SourceStats"][];
            serverstats: components["schemas"]["ServerStats"] | null;
            activity: components["schemas"]["Activity"] | null;
            /** Client Count */
            client_count: number;
        };
        /** Client */
        Client: {
            /** Address */
            address: string;
            /** Ntp Packets */
            ntp_packets: number;
            /** Ntp Dropped */
            ntp_dropped: number;
            /**
             * Ntp Interval
             * @description Average request interval, log2 seconds
             */
            ntp_interval: number | null;
            /**
             * Ntp Last Rx S
             * @description Seconds since the last NTP request
             */
            ntp_last_rx_s: number | null;
            /** Cmd Packets */
            cmd_packets: number;
            /** Cmd Dropped */
            cmd_dropped: number;
            /** Cmd Last Rx S */
            cmd_last_rx_s: number | null;
        };
        /** ConstellationCount */
        ConstellationCount: {
            /** Visible */
            visible: number;
            /** Used */
            used: number;
        };
        /** Dop */
        Dop: {
            /** Gdop */
            gdop?: number | null;
            /** Pdop */
            pdop?: number | null;
            /** Hdop */
            hdop?: number | null;
            /** Vdop */
            vdop?: number | null;
            /** Tdop */
            tdop?: number | null;
        };
        /** GpsDevice */
        GpsDevice: {
            /** Path */
            path?: string | null;
            /** Driver */
            driver?: string | null;
            /** Subtype */
            subtype?: string | null;
            /** Subtype1 */
            subtype1?: string | null;
            /** Bps */
            bps?: number | null;
        };
        /** GpsFix */
        GpsFix: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "unknown" | "no_fix" | "2d" | "3d";
            /**
             * Time
             * @description GPS time of the fix (UTC)
             */
            time: string | null;
            /** Leapseconds */
            leapseconds?: number | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /**
             * Alt Msl M
             * @description Altitude above mean sea level
             */
            alt_msl_m?: number | null;
            /**
             * Alt Hae M
             * @description Altitude above the WGS84 ellipsoid
             */
            alt_hae_m?: number | null;
            /**
             * Eph M
             * @description Estimated horizontal error (95%)
             */
            eph_m?: number | null;
            /**
             * Epv M
             * @description Estimated vertical error (95%)
             */
            epv_m?: number | null;
            /**
             * Ept S
             * @description Estimated time error (95%)
             */
            ept_s?: number | null;
            /** Speed Mps */
            speed_mps?: number | null;
        };
        /** GpsStatus */
        GpsStatus: {
            /**
             * Connected
             * @description Connected to gpsd
             */
            connected: boolean;
            /**
             * Age S
             * @description Seconds since the last gpsd report
             */
            age_s: number | null;
            /** Gpsd Version */
            gpsd_version: string | null;
            device: components["schemas"]["GpsDevice"];
            fix: components["schemas"]["GpsFix"];
            dop: components["schemas"]["Dop"];
            /** Satellites Visible */
            satellites_visible: number;
            /** Satellites Used */
            satellites_used: number;
            /** Constellations */
            constellations: {
                [key: string]: components["schemas"]["ConstellationCount"];
            };
            /** Satellites */
            satellites: components["schemas"]["Satellite"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Gpsd */
            gpsd: boolean;
            /** Chrony */
            chrony: boolean;
        };
        /**
         * HistoryPoint
         * @description A raw sample (ranges up to 24 h) or a bucket average (longer ranges).
         *
         *     For bucket averages `t` is the bucket centre, the other fields are means,
         *     and the offset min/max fields bound what the mean hides.
         */
        HistoryPoint: {
            /**
             * T
             * @description Unix time
             */
            t: number;
            /** System Time Offset S */
            system_time_offset_s: number;
            /** Last Offset S */
            last_offset_s: number;
            /** Rms Offset S */
            rms_offset_s: number;
            /** Frequency Ppm */
            frequency_ppm: number;
            /** Skew Ppm */
            skew_ppm: number;
            /** Pps Offset S */
            pps_offset_s: number | null;
            /** Satellites Used */
            satellites_used: number;
            /** Satellites Visible */
            satellites_visible: number;
            /** Cpu Temp C */
            cpu_temp_c: number | null;
            /** System Time Offset Min S */
            system_time_offset_min_s?: number | null;
            /** System Time Offset Max S */
            system_time_offset_max_s?: number | null;
            /** Pps Offset Min S */
            pps_offset_min_s?: number | null;
            /** Pps Offset Max S */
            pps_offset_max_s?: number | null;
        };
        /** Satellite */
        Satellite: {
            /**
             * Prn
             * @description gpsd PRN (unique across constellations)
             */
            prn: number | null;
            /**
             * Gnss
             * @description GPS, SBAS, Galileo, BeiDou, IMES, QZSS, GLONASS, NavIC
             */
            gnss: string;
            /**
             * Svid
             * @description Satellite id within its constellation
             */
            svid: number | null;
            /**
             * Azimuth
             * @description Degrees from true north
             */
            azimuth: number | null;
            /**
             * Elevation
             * @description Degrees above the horizon
             */
            elevation: number | null;
            /**
             * Snr
             * @description Signal strength, dBHz
             */
            snr: number | null;
            /**
             * Used
             * @description Used in the navigation solution
             */
            used: boolean;
        };
        /** ServerStats */
        ServerStats: {
            /** Ntp Packets Received */
            ntp_packets_received?: number | null;
            /** Ntp Packets Dropped */
            ntp_packets_dropped?: number | null;
            /** Cmd Packets Received */
            cmd_packets_received?: number | null;
            /** Cmd Packets Dropped */
            cmd_packets_dropped?: number | null;
            /** Client Log Records Dropped */
            client_log_records_dropped?: number | null;
            /** Nts Ke Accepted */
            nts_ke_accepted?: number | null;
            /** Nts Ke Dropped */
            nts_ke_dropped?: number | null;
            /** Authenticated Ntp Packets */
            authenticated_ntp_packets?: number | null;
            /** Interleaved Ntp Packets */
            interleaved_ntp_packets?: number | null;
            /** Ntp Timestamps Held */
            ntp_timestamps_held?: number | null;
            /** Ntp Timestamp Span */
            ntp_timestamp_span?: number | null;
            /** Ntp Daemon Rx Timestamps */
            ntp_daemon_rx_timestamps?: number | null;
            /** Ntp Daemon Tx Timestamps */
            ntp_daemon_tx_timestamps?: number | null;
            /** Ntp Kernel Rx Timestamps */
            ntp_kernel_rx_timestamps?: number | null;
            /** Ntp Kernel Tx Timestamps */
            ntp_kernel_tx_timestamps?: number | null;
            /** Ntp Hw Rx Timestamps */
            ntp_hw_rx_timestamps?: number | null;
            /** Ntp Hw Tx Timestamps */
            ntp_hw_tx_timestamps?: number | null;
        };
        /** Source */
        Source: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "server" | "peer" | "refclock";
            /**
             * State
             * @enum {string}
             */
            state: "selected" | "combined" | "not_combined" | "unusable" | "falseticker" | "too_variable";
            /** Name */
            name: string;
            /** Stratum */
            stratum: number;
            /**
             * Poll
             * @description Poll interval, log2 seconds
             */
            poll: number;
            /**
             * Reach
             * @description Bitmask of the last 8 polls (255 = all answered)
             */
            reach: number;
            /**
             * Last Rx S
             * @description Seconds since the last sample
             */
            last_rx_s: number | null;
            /**
             * Offset S
             * @description Last sample offset, adjusted for clock changes since
             */
            offset_s: number;
            /** Measured Offset S */
            measured_offset_s: number;
            /**
             * Error S
             * @description Error margin of the last sample
             */
            error_s: number;
        };
        /** SourceStats */
        SourceStats: {
            /** Name */
            name: string;
            /** Samples */
            samples: number;
            /** Runs */
            runs: number;
            /** Span S */
            span_s: number;
            /** Frequency Ppm */
            frequency_ppm: number;
            /** Freq Skew Ppm */
            freq_skew_ppm: number;
            /** Offset S */
            offset_s: number;
            /** Std Dev S */
            std_dev_s: number;
        };
        /** Status */
        Status: {
            /**
             * Time
             * @description Unix time of this snapshot
             */
            time: number;
            gps: components["schemas"]["GpsStatus"];
            chrony: components["schemas"]["ChronyStatus"];
            system: components["schemas"]["SystemStatus"];
        };
        /** SystemStatus */
        SystemStatus: {
            /** Hostname */
            hostname: string;
            /** Cpu Temp C */
            cpu_temp_c: number | null;
            /**
             * Load
             * @description 1, 5 and 15 minute load averages
             */
            load: number[] | null;
            /** Uptime S */
            uptime_s: number | null;
            /** Mem Total Bytes */
            mem_total_bytes: number | null;
            /** Mem Available Bytes */
            mem_available_bytes: number | null;
        };
        /** Tracking */
        Tracking: {
            /**
             * Ref Id
             * @description Reference id, hex
             */
            ref_id: string;
            /**
             * Ref Name
             * @description Reference source name or address
             */
            ref_name: string;
            /** Stratum */
            stratum: number;
            /**
             * Ref Time
             * @description Unix time of the last reference update
             */
            ref_time: number;
            /**
             * System Time Offset S
             * @description System clock minus true time: + means the clock is ahead
             */
            system_time_offset_s: number;
            /**
             * Last Offset S
             * @description Offset measured at the last clock update
             */
            last_offset_s: number;
            /**
             * Rms Offset S
             * @description Long-term average of the offset
             */
            rms_offset_s: number;
            /**
             * Frequency Ppm
             * @description Local oscillator error: + means it runs fast
             */
            frequency_ppm: number;
            /** Residual Freq Ppm */
            residual_freq_ppm: number;
            /**
             * Skew Ppm
             * @description Error bound of the frequency estimate
             */
            skew_ppm: number;
            /** Root Delay S */
            root_delay_s: number;
            /** Root Dispersion S */
            root_dispersion_s: number;
            /** Update Interval S */
            update_interval_s: number;
            /**
             * Leap Status
             * @description Normal, Insert second, Delete second or Not synchronised
             */
            leap_status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    gps_api_gps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpsStatus"];
                };
            };
        };
    };
    satellites_api_gps_satellites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Satellite"][];
                };
            };
        };
    };
    chrony_api_chrony_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChronyStatus"];
                };
            };
        };
    };
    clients_api_chrony_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                };
            };
        };
    };
    system_api_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: {
                minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description gpsd or chronyd unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
